interface heritage {
  name: string;
  type: string;
  designation: string;
  designationYear: number;
  region: string;
  era: string;
  imageUrl: string;
  address?: string;
}

const heritageData: heritage[] = [
  {
    name: "경복궁",
    type: "궁궐",
    designation: "사적",
    designationYear: 1963,
    region: "서울",
    era: "조선시대",
    imageUrl:
      "https://www.heritage.go.kr/unisearch/images/national_treasure/2021062917265903.jpg",
    address: "서울특별시 종로구 사직로 161",
  },
  {
    name: "석굴암",
    type: "불교 유적",
    designation: "국보",
    designationYear: 1962,
    region: "경상북도 경주",
    era: "통일신라",
    imageUrl:
      "https://www.heritage.go.kr/unisearch/images/national_treasure/2021042208550900.jpg",
    address: "경상북도 경주시 석굴암로 361",
  },
  {
    name: "첨성대",
    type: "천문 관측대",
    designation: "국보",
    designationYear: 1962,
    region: "경상북도 경주",
    era: "신라",
    imageUrl:
      "https://www.heritage.go.kr/unisearch/images/national_treasure/2021032415274702.JPG",
    address: "경상북도 경주시 조선로 162",
  },
  {
    name: "종묘",
    type: "제례 시설",
    designation: "세계유산",
    designationYear: 1995,
    region: "서울",
    era: "조선시대",
    imageUrl:
      "https://www.heritage.go.kr/unisearch/images/national_treasure/2021063016361203.jpg",
    address: "서울특별시 종로구 종로 155",
  },
  //   {
  //     name: "해인사 장경판전",
  //     type: "사찰",
  //     designation: "국보",
  //     designationYear: 1995,
  //     region: "경상남도 합천",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/haeinsa.jpg",
  //     address: "경상남도 합천군 해인사로 108",
  //   },
  //   {
  //     name: "팔만대장경",
  //     type: "기록물",
  //     designation: "세계기록유산",
  //     designationYear: 2007,
  //     region: "경상남도 합천",
  //     era: "고려시대",
  //     imageUrl: "https://example.com/images/palmandaejang.jpg",
  //     address: "경상남도 합천군 대장경로 561",
  //   },
  //   {
  //     name: "안압지",
  //     type: "정원",
  //     designation: "사적",
  //     designationYear: 1974,
  //     region: "경상북도 경주",
  //     era: "신라",
  //     imageUrl: "https://example.com/images/anapji.jpg",
  //     address: "경상북도 경주시 안압지로 38",
  //   },
  //   {
  //     name: "경주 불국사",
  //     type: "사찰",
  //     designation: "세계유산",
  //     designationYear: 1995,
  //     region: "경상북도 경주",
  //     era: "통일신라",
  //     imageUrl: "https://example.com/images/bulguksa.jpg",
  //     address: "경상북도 경주시 불국로 385",
  //   },
  //   {
  //     name: "창덕궁",
  //     type: "궁궐",
  //     designation: "세계유산",
  //     designationYear: 1997,
  //     region: "서울",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/changdeokgung.jpg",
  //     address: "서울특별시 종로구 창덕궁로 99",
  //   },
  //   {
  //     name: "수원 화성",
  //     type: "성곽",
  //     designation: "세계유산",
  //     designationYear: 1997,
  //     region: "경기도 수원",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/suwonhwaseong.jpg",
  //     address: "경기도 수원시 팔달구 화성로 551",
  //   },
  //   {
  //     name: "덕수궁",
  //     type: "궁궐",
  //     designation: "사적",
  //     designationYear: 1985,
  //     region: "서울",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/deoksugung.jpg",
  //     address: "서울특별시 중구 세종대로 99",
  //   },
  //   {
  //     name: "광화문",
  //     type: "문루",
  //     designation: "보물",
  //     designationYear: 1963,
  //     region: "서울",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/gwanghwamun.jpg",
  //     address: "서울특별시 종로구 세종대로 175",
  //   },
  //   {
  //     name: "백제 무령왕릉",
  //     type: "왕릉",
  //     designation: "세계유산",
  //     designationYear: 2015,
  //     region: "충청남도 공주",
  //     era: "백제",
  //     imageUrl: "https://example.com/images/muryungwangreung.jpg",
  //     address: "충청남도 공주시 무령왕릉로 19",
  //   },
  //   {
  //     name: "남한산성",
  //     type: "산성",
  //     designation: "세계유산",
  //     designationYear: 2014,
  //     region: "경기도 광주",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/namhansanseong.jpg",
  //     address: "경기도 광주시 남한산성면 산성리 1",
  //   },
  //   {
  //     name: "강릉 오죽헌",
  //     type: "고택",
  //     designation: "보물",
  //     designationYear: 1963,
  //     region: "강원도 강릉",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/ojukheon.jpg",
  //     address: "강원도 강릉시 오죽헌길 24",
  //   },
  //   {
  //     name: "부산 범어사",
  //     type: "사찰",
  //     designation: "사적",
  //     designationYear: 1972,
  //     region: "부산",
  //     era: "신라",
  //     imageUrl: "https://example.com/images/beomeosa.jpg",
  //     address: "부산광역시 금정구 범어사로 250",
  //   },
  //   {
  //     name: "제주 성산일출봉",
  //     type: "자연경관",
  //     designation: "세계자연유산",
  //     designationYear: 2007,
  //     region: "제주도",
  //     era: "선사시대",
  //     imageUrl: "https://example.com/images/seongsanilchulbong.jpg",
  //     address: "제주특별자치도 서귀포시 성산읍 성산리 1",
  //   },
  //   {
  //     name: "평양 대동문",
  //     type: "문루",
  //     designation: "보물",
  //     designationYear: 1936,
  //     region: "평양",
  //     era: "고구려",
  //     imageUrl: "https://example.com/images/daedongmun.jpg",
  //     address: "평양시 대동문로",
  //   },
  //   {
  //     name: "밀양 표충사",
  //     type: "사찰",
  //     designation: "사적",
  //     designationYear: 1972,
  //     region: "경상남도 밀양",
  //     era: "통일신라",
  //     imageUrl: "https://example.com/images/pyochungsa.jpg",
  //     address: "경상남도 밀양시 표충로 85",
  //   },
  //   {
  //     name: "제주 만장굴",
  //     type: "동굴",
  //     designation: "세계자연유산",
  //     designationYear: 2007,
  //     region: "제주도",
  //     era: "선사시대",
  //     imageUrl: "https://example.com/images/manjanggul.jpg",
  //     address: "제주특별자치도 제주시 구좌읍 만장굴길 88",
  //   },
  //   {
  //     name: "강강술래",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1966,
  //     region: "전국",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/kanggangsullae.jpg",
  //     address: "전국",
  //   },
  //   {
  //     name: "판소리",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1964,
  //     region: "전국",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/pansori.jpg",
  //     address: "전국",
  //   },

  //   {
  //     name: "아리랑",
  //     type: "무형유산",
  //     designation: "세계유산",
  //     designationYear: 2012,
  //     region: "전국",
  //     era: "전통",
  //     imageUrl: "https://example.com/images/arirang.jpg",
  //   },
  //   {
  //     name: "줄타기",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1970,
  //     region: "전국",
  //     era: "전통",
  //     imageUrl: "https://example.com/images/jultagi.jpg",
  //   },
  //   {
  //     name: "택견",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1983,
  //     region: "전국",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/taekkyon.jpg",
  //   },
  //   {
  //     name: "김장문화",
  //     type: "무형유산",
  //     designation: "세계유산",
  //     designationYear: 2013,
  //     region: "전국",
  //     era: "현대",
  //     imageUrl: "https://example.com/images/kimjang.jpg",
  //   },
  //   {
  //     name: "한산 모시짜기",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1967,
  //     region: "충청남도 서천",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/hansanmosi.jpg",
  //   },
  //   {
  //     name: "제주 칠머리당 영등굿",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1980,
  //     region: "제주도",
  //     era: "전통",
  //     imageUrl: "https://example.com/images/yeongdeunggut.jpg",
  //   },
  //   {
  //     name: "하회탈춤",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1980,
  //     region: "경상북도 안동",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/hahoetancheum.jpg",
  //   },
  //   {
  //     name: "강릉 단오제",
  //     type: "무형유산",
  //     designation: "세계유산",
  //     designationYear: 2005,
  //     region: "강원도 강릉",
  //     era: "전통",
  //     imageUrl: "https://example.com/images/gangneungdano.jpg",
  //   },
  //   {
  //     name: "남사당놀이",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1988,
  //     region: "전국",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/namsadang.jpg",
  //   },
  //   {
  //     name: "봉산 탈춤",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1970,
  //     region: "황해도 봉산",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/bongsantalchum.jpg",
  //   },
  //   {
  //     name: "매사냥",
  //     type: "무형유산",
  //     designation: "세계유산",
  //     designationYear: 2010,
  //     region: "전국",
  //     era: "전통",
  //     imageUrl: "https://example.com/images/maesanyang.jpg",
  //   },
  //   {
  //     name: "옹기 제작",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1997,
  //     region: "전국",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/onggi.jpg",
  //   },
  //   {
  //     name: "전통 떡 만들기",
  //     type: "무형유산",
  //     designation: "세계유산",
  //     designationYear: 2018,
  //     region: "전국",
  //     era: "전통",
  //     imageUrl: "https://example.com/images/traditionaltteok.jpg",
  //   },
  //   {
  //     name: "제주 해녀 문화",
  //     type: "무형유산",
  //     designation: "세계유산",
  //     designationYear: 2016,
  //     region: "제주도",
  //     era: "전통",
  //     imageUrl: "https://example.com/images/jejuhaenyeo.jpg",
  //   },
  //   {
  //     name: "안동 소주 빚기",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1980,
  //     region: "경상북도 안동",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/andongsoju.jpg",
  //   },
  //   {
  //     name: "가야금 연주",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1971,
  //     region: "전국",
  //     era: "조선시대",
  //     imageUrl: "https://example.com/images/gayageum.jpg",
  //   },
  //   {
  //     name: "태평무",
  //     type: "무형유산",
  //     designation: "중요무형문화재",
  //     designationYear: 1974,
  //     region: "전국",
  //     era: "전통",
  //     imageUrl: "https://example.com/images/taepyeongmu.jpg",
  //   },
  //   {
  //     name: "강화 매화마름 군락지",
  //     type: "천연기념물",
  //     designation: "천연기념물",
  //     designationYear: 1973,
  //     region: "인천 강화",
  //     era: "자연",
  //     imageUrl: "https://example.com/images/maehwamareum.jpg",
  //     address: "인천광역시 강화군 길상면 매화리 일대",
  //   },
  //   {
  //     name: "설악산 주목 군락지",
  //     type: "천연기념물",
  //     designation: "천연기념물",
  //     designationYear: 1965,
  //     region: "강원도 설악산",
  //     era: "자연",
  //     imageUrl: "https://example.com/images/seoraksan.jpg",
  //     address: "강원도 속초시 설악산 일대 (설악산 국립공원 내)",
  //   },
  //   {
  //     name: "제주 비자나무 군락지",
  //     type: "천연기념물",
  //     designation: "천연기념물",
  //     designationYear: 1962,
  //     region: "제주도",
  //     era: "자연",
  //     imageUrl: "https://example.com/images/bijanamu.jpg",
  //     address: "제주특별자치도 제주시 한림읍 금능리 일대",
  //   },
];

export default heritageData;
